from fractal import CIFS
from cmath import sin, cos, exp, sinh, cosh

man = CIFS([500, 500])
man.setRange(20, 20)
man.setRadius(5)
# man.setFunction(lambda z: exp(z) * cos(z))
# man.setFunction(lambda z: cos(exp(z)))
# man.setFunction(lambda z: sin(exp(z)))
# man.setFunction(lambda z: sin(cos(z)))
# man.setFunction(lambda z: exp(sin(z)))
# man.setFunction(lambda z: exp(cos(z)))
# man.setFunction(lambda z: sin(z)*cosh(z))
# man.setFunction(lambda z: sinh(z**2))
# man.setFunction(lambda z: sinh(z**3))
# man.setFunction(lambda z: sinh(z**4))
# man.setFunction(lambda z: sin(z**2))
# man.setFunction(lambda z: sin(z**3))
# man.setFunction(lambda z: z**sin(z))
# man.setFunction(lambda z: z**cos(z))
man.setFunction(lambda z: z**sin(z) + z**cos(z))
# man.setFunction(lambda z: exp(z) - z ** z)
man.doCifs(150)
man.wait()
